# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-24 22:04
from __future__ import unicode_literals

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Client10',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('modified', models.DateTimeField(auto_now=True)),
                ('fname', models.CharField(db_index=True, max_length=200)),
                ('lname', models.CharField(db_index=True, max_length=200)),
                ('birthdate', models.DateField(db_index=True, default=datetime.datetime(2004, 3, 17, 12, 4, 57, 797494))),
                ('mname', models.CharField(blank=True, max_length=200, null=True)),
                ('preffname', models.CharField(blank=True, max_length=200, null=True)),
                ('preflname', models.CharField(blank=True, max_length=200, null=True)),
                ('prefmname', models.CharField(blank=True, max_length=200, null=True)),
                ('ssn', models.CharField(blank=True, max_length=11, null=True)),
                ('clientNbr', models.CharField(blank=True, max_length=10, null=True)),
                ('addr1', models.CharField(blank=True, max_length=400, null=True)),
                ('addr2', models.CharField(blank=True, max_length=400, null=True)),
                ('city', models.CharField(blank=True, max_length=400, null=True)),
                ('state', models.CharField(blank=True, max_length=400, null=True)),
                ('zipcode', models.CharField(blank=True, max_length=20, null=True)),
                ('phone1', models.CharField(blank=True, max_length=20, null=True)),
                ('phone2', models.CharField(blank=True, max_length=20, null=True)),
                ('email', models.CharField(blank=True, max_length=400, null=True)),
                ('emergencyname', models.CharField(blank=True, max_length=400, null=True)),
                ('emergencyrelate', models.CharField(blank=True, max_length=400, null=True)),
                ('emergencyphone', models.CharField(blank=True, max_length=20, null=True)),
                ('genderbirth', models.CharField(max_length=20)),
                ('gendercurrent', models.CharField(max_length=20)),
                ('preferpronoun', models.CharField(blank=True, max_length=20, null=True)),
                ('isuscitizen', models.BooleanField(default=True)),
                ('healthins', models.CharField(max_length=20)),
                ('ise2client', models.BooleanField(default=False)),
                ('ismanagedclient', models.BooleanField(default=False)),
                ('iskuannacompleted', models.BooleanField(default=False)),
                ('ethnicity', models.CharField(choices=[('nt', 'Native American'), ('hi', 'Hawaiian, Fijian, Maori, Samoan, Tahitian, Tongan'), ('af', 'African American/Black'), ('wt', 'Caucasian/White'), ('sa', 'Southeast Asian including Laotian, Thai, Malaysian, Vietnamese, Chinese, Taiwanese, and Filipino'), ('jp', 'Japanese including Okinawan'), ('kr', 'Korean'), ('cb', 'Cuban'), ('mx', 'Mexican, Puerto Rican, Chamorrow, Chuukese, Guaanian, Kosraean, Marshallese'), ('ot', 'Other'), ('dk', 'Dont know, Not sure, Refused'), ('na', 'Not Asked')], max_length=2)),
                ('lfcreateuser', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['fname', 'created'],
            },
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(default='', max_length=100)),
                ('city', models.CharField(default='', max_length=100)),
                ('website', models.URLField(default='')),
                ('phone', models.CharField(default='', max_length=15)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
