# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-12-06 05:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('c1app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client10',
            name='birthdate',
            field=models.DateField(db_index=True, default=datetime.datetime(2004, 3, 28, 19, 22, 38, 30997)),
        ),
    ]
